version: "2"
# ansible overrides passwords and sets empty values on deploy
services:
  postgres:
    image: postgres:9.5
    ports:
      - 5432:5432
    volumes:
      - /home/deploy/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cachet
  cachet:
    build: .
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/deploy/certs/:/etc/nginx/ssl/
    links:
      - postgres:postgres
    environment:
      - DB_DRIVER=pgsql
      - DB_HOST=postgres
      - DB_DATABASE=cachet
      - DB_USERNAME=postgres
      - DB_PASSWORD=
      - QUEUE_DRIVER=database
      - MAIL_DRIVER=sendgrid
      # sendgrid mail_driver uses the API
      - SENDGRID_API_KEY=
      - MAIL_HOST=smtp.sendgrid.net
      - MAIL_PORT=587
      - MAIL_USERNAME=prstatus
      - MAIL_PASSWORD=
      - MAIL_ADDRESS=status@primerevenue.com
      - MAIL_NAME=PrimeRevenue Status Page
      - MAIL_ENCRYPTION=tls
      - APP_ENV=production

    depends_on:
        - postgres    
