version: "2"

services:
  postgres:
    image: postgres:9.5
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  cachet:
    build: .
    ports:
      - 80:80
      - 443:443
    volumes:
      # we need to be careful with this mapping. /etc/ssl is where Debian / Ubuntu keeps it's CACerts so this works because it inherits them from the host system.
      # - /home/deploy/ssl:/etc/nginx/ssl with the appropriate nginx conf modifications is probably safer.
      - /etc/ssl/:/etc/ssl/
    links:
      - postgres:postgres
    environment:
      - DB_DRIVER=pgsql
      - DB_HOST=postgres
      - DB_DATABASE=cachet
      - DB_USERNAME=postgres
      - DB_PASSWORD=
      - QUEUE_DRIVER=database
      - MAIL_DRIVER=smtp
      - MAIL_HOST=smtp.sendgrid.net
      - MAIL_PORT=587
      - MAIL_USERNAME=prstatus
      - MAIL_PASSWORD=
      - MAIL_ADDRESS=status@primerevenue.com
      - MAIL_NAME=Prime Revenue Status Page
      - MAIL_ENCRYPTION=tls
      - APP_ENV=production
    depends_on:
        - postgres    
